 # You can omit this if you prefer not to specify a version

services:
  app:
    image: shaheel456/backendtest:latest  # Your backend image
    ports:
      - "5000:5000"  # Map port 3000 of the container to port 3000 on the host
    environment:
      MONGO_URL: ${MONGO_URL}  # MongoDB connection string, loaded from .env or GitHub Secrets
    depends_on:
      - mongodb  # Ensure mongodb starts before the app
  
  mongodb:
    image: mongo  # Use the official MongoDB image
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

volumes:
  mongo-data:  # Define a volume for MongoDB data persistence
