name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Grant write permission for contents

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm run build --if-present  # Ensure the build step creates the dist folder

    - name: Build Docker Compose
      run: |
        docker-compose -f docker-compose.yml build  # Build the services defined in the docker-compose file

    - name: Start Application
      run: |
        docker-compose up -d  # Start your application and MongoDB service

    - name: Wait for MongoDB
      run: |
        sleep 10  # Wait for MongoDB to start

    - name: Verify Metrics Endpoint
      run: |
        curl -f http://localhost:5000/metrics

    - name: Shutdown Application
      run: |
        docker-compose down  # Stop the services
