name: Docker Compose Action

on:
  push:
    branches: [ "main" ]  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Check out the code from the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for building Docker images

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password from GitHub Secrets

      - name: Build and push Docker image
        uses: docker/build-push-action@v3  # Build and push Docker images
        with:
          context: .  # Build context set to the root of the repository
          file: ./Dockerfile  # Path to your Dockerfile
          push: true  # Push the built image to Docker Hub
          tags: shaheel456/backendtest:latest  # Tag for the Docker image

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1  # Run your services defined in docker-compose
        with:
          compose-file: "./docker/docker-compose.yml"  # Path to your docker-compose file
        env:
          MONGO_URL: "mongodb://mongodb:27017/AuthService"  # Example of a MongoDB connection string
          