name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Grant write permission for contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: shaheel456/backendtest

    - name: Run Docker Compose
      run: |
        docker-compose up -d  # Start your application and MongoDB service
        docker-compose logs    # Show logs to verify everything is running

    - name: Verify Metrics Endpoint
      run: |
        curl -f http://localhost:5000/metrics

    - name: Shut down Docker Compose
      run: |
        docker-compose down  # Clean up the environment after testing
